apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: banking-app
  labels:
    app: profile
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
        version: v1
    spec:
      containers:
      - name: profile
        image: imeshai/demo-bank-profile:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APP_VERSION
          value: "v1"
