apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30306