apiVersion: v1
kind: Namespace
metadata:
  name: multi-cluster
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: multi-cluster
  labels:
    app: profile
    service: profile
spec:
  ports:
  - port: 8081
    name: http
    targetPort: 8081
  selector:
    app: profile