apiVersion: v1
kind: Namespace
metadata:
  name: banking-multi-cluster
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: banking-multi-cluster
  labels:
    app: account
    service: account
spec:
  ports:
  - port: 8082
    name: http
    targetPort: 8082
  selector:
    app: account